# Generated by Django 3.0.6 on 2020-09-30 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 12, 46, 12, 174044)),
        ),
    ]
