# Generated by Django 3.0.6 on 2020-10-02 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john1', '0002_auto_20200930_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 11, 38, 59, 268517)),
        ),
    ]
