# Generated by Django 3.0.6 on 2020-10-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john1', '0003_auto_20201002_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 16, 1, 6, 807656)),
        ),
    ]
