# Generated by Django 3.0.6 on 2020-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beauty_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='pics')),
                ('price', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='pics')),
                ('price', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='pics')),
                ('price', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utencils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='pics')),
                ('price', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Ecommerce',
        ),
    ]
