# Generated by Django 3.0.6 on 2020-10-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20201014_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauty_products',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='utencils',
            name='price',
            field=models.IntegerField(),
        ),
    ]
