# Generated by Django 3.0.6 on 2020-11-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20201104_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortitle', models.CharField(max_length=255)),
                ('ordesc', models.TextField()),
                ('orimg', models.ImageField(upload_to='ordered_products')),
                ('orqnty', models.IntegerField()),
                ('oraddress', models.CharField(max_length=255)),
                ('orpin', models.IntegerField()),
                ('ordist', models.CharField(max_length=255)),
                ('orcntry', models.CharField(max_length=255)),
                ('orprice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Clothes_ProductDetail',
        ),
        migrations.DeleteModel(
            name='Electronics_ProductDetail',
        ),
        migrations.DeleteModel(
            name='Utencils_ProductDetail',
        ),
    ]
