# Generated by Django 3.0.6 on 2020-11-05 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_john', '0003_auto_20201012_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 19, 31, 1, 389251)),
        ),
    ]
